export const docStyles = {
  page: {
    flexDirection: "row",
    backgroundColor: "white",
    fontSize: 12,
    paddingBottom: 80,
    paddingTop: 33.63,
    paddingLeft: 80.6,
    paddingRight: 53.6,
    flexDirection: "column",
    position: "relative",
    lineHeight: 1.5,
  },
  office: {
    marginLeft: "50%",
    textAlign: "justify",
    marginTop: 33,
    fontFamily: "Helvetica",
  },
  header: { width: "100%", height: "140px", textAlign: "center" },
  insignia: { maxHeight: 80, maxWidth: 80, margin: "auto" },
  underlinedBoldText: {
    fontFamily: "Helvetica-Bold",
    textDecoration: "underline",
  },
  city: {
    margin: "auto",
    marginTop: 15,
    textDecoration: "underline",
    fontFamily: "Helvetica-Bold",
  },
  reference: {
    marginTop: 33,
    textAlign: "justify",
    display: "flex",
    flexDirection: "row",
    marginRight: 60,
  },
  subject: {
    marginTop: 15,
    textAlign: "justify",
    display: "flex",
    flexDirection: "row",
    marginRight: 60,
    marginBottom: 15,
  },
  signature: {
    textAlign: "center",
    marginTop: 15,
    fontFamily: "Helvetica-Bold",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
    position: "absolute",
    bottom: 33.6,
    left: 80.8,
    width: "100%",
    borderLeft: 0.8,
    fontSize: 8,
    lineHeight: 1,
  },
  logo: {
    maxHeight: 80,
    maxWidth: 80,
    margin: "auto",
    paddingRight: 6,
  },
  logoWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
};
